EXECUTE sp_unbindrule 'academicos.periodo_ing' 
EXECUTE sp_unbindrule 'academicos.periodo_egre' 
EXECUTE sp_unbindrule 'academicos_hist.periodo_ing' 
EXECUTE sp_unbindrule 'academicos_hist.periodo_egre' 
EXECUTE sp_unbindrule 'academicos2.periodo_ing' 
EXECUTE sp_unbindrule 'academicos2.periodo_egre' 
EXECUTE sp_unbindrule 'activacion.periodo' 
EXECUTE sp_unbindrule 'alumno_examen_gral_con.periodo' 
EXECUTE sp_unbindrule 'aspirantes_revalidacion.periodo_ing' 
EXECUTE sp_unbindrule 'bajas_mat_inscritas.periodo' 
EXECUTE sp_unbindrule 'bit_academicos_hist.periodo_ing' 
EXECUTE sp_unbindrule 'bit_academicos_hist.periodo_egre' 
EXECUTE sp_unbindrule 'bit_grupos.periodo' 
EXECUTE sp_unbindrule 'bit_historico_intercambio.periodo' 
EXECUTE sp_unbindrule 'bit_horario.periodo' 
EXECUTE sp_unbindrule 'calendario.periodo' 
EXECUTE sp_unbindrule 'cortes.periodo' 
EXECUTE sp_unbindrule 'cuentas_cortes.periodo' 
EXECUTE sp_unbindrule 'examen_extrao_titulo.periodo' 
EXECUTE sp_unbindrule 'examen_extrao_titulo_temp.periodo' 
EXECUTE sp_unbindrule 'examen_gral_conocimientos.periodo' 
EXECUTE sp_unbindrule 'folio_monedas.periodo' 
EXECUTE sp_unbindrule 'grupo_sinodal_ets.periodo' 
EXECUTE sp_unbindrule 'grupos.periodo' 
EXECUTE sp_unbindrule 'grupos2.periodo' 
EXECUTE sp_unbindrule 'hist_academicos.periodo_ing' 
EXECUTE sp_unbindrule 'hist_academicos.periodo_egre' 
EXECUTE sp_unbindrule 'hist_adjunto.periodo' 
EXECUTE sp_unbindrule 'hist_carreras.periodo_ing' 
EXECUTE sp_unbindrule 'hist_carreras.periodo_egre_ant' 
EXECUTE sp_unbindrule 'hist_carreras.periodo_ing_act' 
EXECUTE sp_unbindrule 'hist_cuentas_cortes.periodo' 
EXECUTE sp_unbindrule 'hist_grupos.periodo' 
EXECUTE sp_unbindrule 'hist_horario.periodo' 
EXECUTE sp_unbindrule 'hist_indulto.periodo' 
EXECUTE sp_unbindrule 'hist_mat_inscritas.periodo' 
EXECUTE sp_unbindrule 'hist_profesor_lista_asistencia.periodo' 
EXECUTE sp_unbindrule 'hist_reingreso.periodo_ing' 
EXECUTE sp_unbindrule 'historico.periodo' 
EXECUTE sp_unbindrule 'historico_intercambio.periodo' 
EXECUTE sp_unbindrule 'historico_pos_re.periodo' 
EXECUTE sp_unbindrule 'historico_re.periodo' 
EXECUTE sp_unbindrule 'historico_temp_intercambio.periodo' 
EXECUTE sp_unbindrule 'horario.periodo' 
EXECUTE sp_unbindrule 'horario_altas.periodo' 
EXECUTE sp_unbindrule 'mat_inscritas.periodo' 
EXECUTE sp_unbindrule 'mat_preinsc.periodo' 
EXECUTE sp_unbindrule 'materias_revalidacion.periodo' 
EXECUTE sp_unbindrule 'movhistorico.periodo' 
EXECUTE sp_unbindrule 'movimiento_prof_asig.periodo' 
EXECUTE sp_unbindrule 'movmat_inscritas.periodo' 
EXECUTE sp_unbindrule 'movmat_preinsc.periodo' 
EXECUTE sp_unbindrule 'no_academicos_hist.periodo_ing' 
EXECUTE sp_unbindrule 'no_academicos_hist.periodo_egre' 
EXECUTE sp_unbindrule 'periodo.periodo' 
EXECUTE sp_unbindrule 'periodos.periodo' 
EXECUTE sp_unbindrule 'periodos_por_procesos.periodo' 
EXECUTE sp_unbindrule 'plan_estudios.periodo_ini' 
EXECUTE sp_unbindrule 'plan_estudios.periodo_vigencia' 
EXECUTE sp_unbindrule 'profesor_lista_asistencia.periodo' 
EXECUTE sp_unbindrule 'sfeb_sqp_historico.periodo' 
EXECUTE sp_unbindrule 'sg_grupos.periodo' 
EXECUTE sp_unbindrule 'sg_grupos_cambio_cupo.periodo' 
EXECUTE sp_unbindrule 'sg_horario.periodo' 
EXECUTE sp_unbindrule 'ui_bibaj.periodo' 
EXECUTE sp_unbindrule 'ui_bicamnot.periodo' 
EXECUTE sp_unbindrule tipo_periodo
GO


IF OBJECT_ID ('dbo.regla_periodo') IS NOT NULL
	DROP RULE dbo.regla_periodo
GO

CREATE RULE dbo.regla_periodo AS @tipo_periodo IN (7,8,9)
GO

EXECUTE sp_bindrule regla_periodo, 'academicos.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'academicos.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'academicos.periodo_egre' 
EXECUTE sp_bindrule regla_periodo, 'academicos_hist.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'academicos_hist.periodo_egre' 
EXECUTE sp_bindrule regla_periodo, 'academicos2.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'academicos2.periodo_egre' 
EXECUTE sp_bindrule regla_periodo, 'activacion.periodo' 
EXECUTE sp_bindrule regla_periodo, 'alumno_examen_gral_con.periodo' 
EXECUTE sp_bindrule regla_periodo, 'aspirantes_revalidacion.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'bajas_mat_inscritas.periodo' 
EXECUTE sp_bindrule regla_periodo, 'bit_academicos_hist.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'bit_academicos_hist.periodo_egre' 
EXECUTE sp_bindrule regla_periodo, 'bit_grupos.periodo' 
EXECUTE sp_bindrule regla_periodo, 'bit_historico_intercambio.periodo' 
EXECUTE sp_bindrule regla_periodo, 'bit_horario.periodo' 
EXECUTE sp_bindrule regla_periodo, 'calendario.periodo' 
EXECUTE sp_bindrule regla_periodo, 'cortes.periodo' 
EXECUTE sp_bindrule regla_periodo, 'cuentas_cortes.periodo' 
EXECUTE sp_bindrule regla_periodo, 'examen_extrao_titulo.periodo' 
EXECUTE sp_bindrule regla_periodo, 'examen_extrao_titulo_temp.periodo' 
EXECUTE sp_bindrule regla_periodo, 'examen_gral_conocimientos.periodo' 
EXECUTE sp_bindrule regla_periodo, 'folio_monedas.periodo' 
EXECUTE sp_bindrule regla_periodo, 'grupo_sinodal_ets.periodo' 
EXECUTE sp_bindrule regla_periodo, 'grupos.periodo' 
EXECUTE sp_bindrule regla_periodo, 'grupos2.periodo' 
EXECUTE sp_bindrule regla_periodo, 'hist_academicos.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'hist_academicos.periodo_egre' 
EXECUTE sp_bindrule regla_periodo, 'hist_adjunto.periodo' 
EXECUTE sp_bindrule regla_periodo, 'hist_carreras.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'hist_carreras.periodo_egre_ant' 
EXECUTE sp_bindrule regla_periodo, 'hist_carreras.periodo_ing_act' 
EXECUTE sp_bindrule regla_periodo, 'hist_cuentas_cortes.periodo' 
EXECUTE sp_bindrule regla_periodo, 'hist_grupos.periodo' 
EXECUTE sp_bindrule regla_periodo, 'hist_horario.periodo' 
EXECUTE sp_bindrule regla_periodo, 'hist_indulto.periodo' 
EXECUTE sp_bindrule regla_periodo, 'hist_mat_inscritas.periodo' 
EXECUTE sp_bindrule regla_periodo, 'hist_profesor_lista_asistencia.periodo' 
EXECUTE sp_bindrule regla_periodo, 'hist_reingreso.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'historico.periodo' 
EXECUTE sp_bindrule regla_periodo, 'historico_intercambio.periodo' 
EXECUTE sp_bindrule regla_periodo, 'historico_pos_re.periodo' 
EXECUTE sp_bindrule regla_periodo, 'historico_re.periodo' 
EXECUTE sp_bindrule regla_periodo, 'historico_temp_intercambio.periodo' 
EXECUTE sp_bindrule regla_periodo, 'horario.periodo' 
EXECUTE sp_bindrule regla_periodo, 'horario_altas.periodo' 
EXECUTE sp_bindrule regla_periodo, 'mat_inscritas.periodo' 
EXECUTE sp_bindrule regla_periodo, 'mat_preinsc.periodo' 
EXECUTE sp_bindrule regla_periodo, 'materias_revalidacion.periodo' 
EXECUTE sp_bindrule regla_periodo, 'movhistorico.periodo' 
EXECUTE sp_bindrule regla_periodo, 'movimiento_prof_asig.periodo' 
EXECUTE sp_bindrule regla_periodo, 'movmat_inscritas.periodo' 
EXECUTE sp_bindrule regla_periodo, 'movmat_preinsc.periodo' 
EXECUTE sp_bindrule regla_periodo, 'no_academicos_hist.periodo_ing' 
EXECUTE sp_bindrule regla_periodo, 'no_academicos_hist.periodo_egre' 
EXECUTE sp_bindrule regla_periodo, 'periodo.periodo' 
EXECUTE sp_bindrule regla_periodo, 'periodos.periodo' 
EXECUTE sp_bindrule regla_periodo, 'periodos_por_procesos.periodo' 
EXECUTE sp_bindrule regla_periodo, 'plan_estudios.periodo_ini' 
EXECUTE sp_bindrule regla_periodo, 'plan_estudios.periodo_vigencia' 
EXECUTE sp_bindrule regla_periodo, 'profesor_lista_asistencia.periodo' 
EXECUTE sp_bindrule regla_periodo, 'sfeb_sqp_historico.periodo' 
EXECUTE sp_bindrule regla_periodo, 'sg_grupos.periodo' 
EXECUTE sp_bindrule regla_periodo, 'sg_grupos_cambio_cupo.periodo' 
EXECUTE sp_bindrule regla_periodo, 'sg_horario.periodo' 
EXECUTE sp_bindrule regla_periodo, 'ui_bibaj.periodo' 
EXECUTE sp_bindrule regla_periodo, 'ui_bicamnot.periodo' 
EXECUTE sp_bindrule regla_periodo, tipo_periodo
GO